/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as YearRouteImport } from './routes/$year'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MYearMonthRouteImport } from './routes/m/$yearMonth'
import { Route as ApiUploadRouteImport } from './routes/api.upload'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const YearRoute = YearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MYearMonthRoute = MYearMonthRouteImport.update({
  id: '/m/$yearMonth',
  path: '/m/$yearMonth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$year': typeof YearRoute
  '/admin': typeof AdminRoute
  '/api/upload': typeof ApiUploadRoute
  '/m/$yearMonth': typeof MYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$year': typeof YearRoute
  '/admin': typeof AdminRoute
  '/api/upload': typeof ApiUploadRoute
  '/m/$yearMonth': typeof MYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$year': typeof YearRoute
  '/admin': typeof AdminRoute
  '/api/upload': typeof ApiUploadRoute
  '/m/$yearMonth': typeof MYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$year' | '/admin' | '/api/upload' | '/m/$yearMonth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$year' | '/admin' | '/api/upload' | '/m/$yearMonth'
  id: '__root__' | '/' | '/$year' | '/admin' | '/api/upload' | '/m/$yearMonth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YearRoute: typeof YearRoute
  AdminRoute: typeof AdminRoute
  ApiUploadRoute: typeof ApiUploadRoute
  MYearMonthRoute: typeof MYearMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$year': {
      id: '/$year'
      path: '/$year'
      fullPath: '/$year'
      preLoaderRoute: typeof YearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$yearMonth': {
      id: '/m/$yearMonth'
      path: '/m/$yearMonth'
      fullPath: '/m/$yearMonth'
      preLoaderRoute: typeof MYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YearRoute: YearRoute,
  AdminRoute: AdminRoute,
  ApiUploadRoute: ApiUploadRoute,
  MYearMonthRoute: MYearMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
